#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

darwin=false;
case "`uname`" in
  Darwin*) darwin=true ;;
esac

if $darwin; then
  sedi="sed -i ''"
else
  sedi="sed -i"
fi

echo "We are going to enroll your current Atmosphere system as an Agave system"
echo "so you can run apps on it through Agave."
echo "The following assumes you have created an Agave client via client-create."
echo -e "We will now ask you to refresh your access token...\n"

set -e
auth-tokens-create -S
sleep 2

#IPLANT_SDK_HOME="/Users/mwvaughn/agave2-mar-2014/iplant-agave-sdk"

echo "We will now configure a new execution system and need some info from you"
echo -e "\tTACC username"
echo -e "\tTACC password"
echo -e "\tThe path to your \$WORK directory on the VM (usually /home/<username>)"
echo ""

default="Yes"
read -p "Do you have all the information required? [$default]: " READY
READY=${READY:-$default}
if [ "$READY" != "Yes" ]; then exit 1; fi

echo "OK. Let's begin."

default=""
read -p "Enter your TACC user account [$default]: " USERNAME
USERNAME=${USERNAME:-$default}
echo "Confirmed: TACC user account is $USERNAME"

default=""
read -s -p "Enter your TACC account password [$default]: " PASSWORD
PASSWORD=${PASSWORD:-$default}
echo "\n"

default=""
read -p "Enter your TACC work directory [$default]: " WORKD
WORKD=${WORKD:-$default}
echo "Confirmed: TACC work directory is $WORK"

# Create a date stamp to ensure the system name is fairly unique
DATESTAMP=$(date +%m%d%Y-%k%M)
HOSTNAME=$(hostname -s)

for F in $DIR/../templates/tacc-atmo*
do
BN=$(basename $F .jsonx)
cp $F "$BN.json" && chmod 600 $BN.json
echo "$BN.json"
# Find and replace on Macros
$sedi "s/%HOSTNAME/$HOSTNAME/g" "$BN.json"
$sedi "s/%USERNAME/$USERNAME/g" "$BN.json"
$sedi "s/%PASSWORD/$PASSWORD/g" "$BN.json"
$sedi "s/%DATESTAMP/$DATESTAMP/g" "$BN.json"
$sedi "s|%WORK|$WORKD|g" "$BN.json"
echo "Enrolling private system $BN"
systems-addupdate -F "$BN.json"
done
set +e

rm -rf "*.bax"

echo -e ""
echo "Here is a listing of your systems:"
systems-list
